---
title: "Kevin Adoption Rate"
author: "Kevin Cooper (kac4bh)"
date: "4/28/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(caret)
library(tidyverse)
library(class)
library(plotly)
library(mice)
library(MLmetrics)
library(mltools)
library(data.table)
```

```{r}
shelter_init <- read.csv("C:/Users/kcoop/Desktop/CS/Data Science/3001/DS3001Final/animal-shelter-intakes-and-outcomes.csv")

shelter_init[shelter_init == ""] <- NA
abc <- names(select_if(shelter_init, is.character))
# table(abc)
# view(abc)
abc <- abc[-c(1,2,14,7,8,13)]
shelter_init[abc] <- lapply(shelter_init[abc], as.factor)
# str(shelter_init)
# view(shelter_init)
newShelter <- shelter_init[,-c(2,5,7, 9, 13, 14, 19)]
# view(newShelter)
# mice::md.pattern(newShelter)
# summary(newShelter)
# table(newShelter$`Outcome Subtype`)
# sum(is.na(newShelter))
# sum(is.na(shelter_init))

newShelter <- na.omit(newShelter)
# mice::md.pattern(newShelter)
newShelter[c(13,14)] <- lapply(newShelter[c(13,14)], as.factor)
newShelter <- newShelter[,-c(1,8,9,12)]
# sum(is.na(newShelter))
# str(newShelter$Outcome.Subtype)
colnames(newShelter) <- make.names(colnames(newShelter))


#DOB
```

```{r}
newShelter$Animal.Type <- fct_collapse(newShelter$Animal.Type, 
                           Other = c("AMPHIBIAN", "BIRD", "GUINEA PIG", "LIVESTOCK", "OTHER", "RABBIT", "REPTILE", "WILD"),
                           # Cat = c("CAT"),
                           # Dog = c("DOG")
                           )

newShelter$Primary.Color <- fct_collapse(newShelter$Primary.Color,
                           Orange = c("APRICOT",  "BLONDE", "CR LYNX PT", "CREAM", "CREAM PT", "CRM TABBY", "CRM TIGER",
                                      "FAWN", "FLAME PT", "GOLD", "ORANGE", "ORG TABBY", "ORG TIGER", "PEACH", "WHEAT",
                                      "Y BRINDLE", "YELLOW"),
                           Other = c("B-C PT", "BL BRINDLE", "BL LYNX PT", "BC LYNX PT", "BLUE","BLUE BRIND", "BLUE CREAM",
                                     "BLUE MERLE","BLUE PT", "BLUE TABBY", "BLUE TICK", "BUFF", "C-T PT", "CALICO", 
                                     "CALICO DIL", "CALICO PT", "CALICO TAB", "DAPPLE", "GREEN","L-C PT", "LC LYNX PT", 
                                     "LI LYNX PT", "LILAC PT", "LIVER", "LIVER TICK", "LYNX PT", "PINK", "RD LYNX PT",
                                     "RED", "RED MERLE", "RUDDY", "S-T PT", "SABLE", "SEAL", "SEAL PT", "ST LYNX PT",
                                     "TORBI", "TORTIE", "TORTIE DIL", "TORTIE MUT", "TORTIE PT", "TRICOLOR", "UNKNOWN"),
                           Black = c("BLACK","BLK SMOKE", "BLK TABBY", "BLK TIGER"),
                           Brown_Tan = c("BR BRINDLE", "BRN MERLE", "BRN TABBY", "BRN TIGER", "BROWN", "CHOC PT",
                                         "CHOCOLATE", "SEAL", "SEAL PT",
                                         "TAN"),
                           Gray_White = c("GRAY", "GRAY TABBY", "GRAY TIGER", "WHITE", "SILVER", "SL LYNX PT", 
                                          "SLVR TABBY", "SNOWSHOE"))
table(newShelter$Intake.Type)
newShelter$Intake.Condition <- fct_collapse(newShelter$Intake.Condition, 
                           Other = c("AGED", "UNDER AGE/WEIGHT", "LIVESTOCK", "OTHER", "RABBIT", "REPTILE", "WILD", "WELFARE SEIZURES"),
                           Behavior = c("BEHAVIOR  MILD", "BEHAVIOR  MODERATE", "BEHAVIOR  SEVERE", "FERAL", "FRACTIOUS"),
                           Ill_Injured = c("ILL MILD", "ILL MODERATETE", "ILL SEVERE", "INJURED  MILD", "INJURED  MODERATE", "INJURED  SEVERE"),
                           # Normal = c("NORMAL")
                           )

newShelter$Intake.Type <- fct_collapse(newShelter$Intake.Type, 
                           # Owner_Surrender = c("OWNER SURRENDER"),
                           # Stray = c("STRAY"),
                           # Wildlife = c("WILDLIFE"),
                           Other = c("OWNER SURRENDER", "CONFISCATE", "Euthenasia Required", "FOSTER", "RETURN", "SAFE KEEP", "WELFARE SEIZED", "Adopted Animal Return",
                                     "QUARANTINE", "TRAP, NEUTER, RETURN"))
# table(newShelter$Jurisdiction)

newShelter$Jurisdiction <- fct_collapse(newShelter$Jurisdiction, 
                           LA = c("LA CITY", "LA COUNTY", "SIGNAL HILL", "TORRANCE AC"),
                           OC = c("ORANGE CNTY", "SEAL BEACH", "CERRITOS", "IRVINE", "GARDEN GROVE", 
                                  "LA HABRA", "LOS ALAMITOS", "SEAACA", "WESTMINSTER"),
                           LB= c("LONG BEACH", "DISTRICT1", "DISTRICT2", "DISTRICT3", "DISTRICT4", "DISTRICT5", 
                                 "DISTRICT6", "DISTRICT7", "DISTRICT8", "DISTRICT9"),
                           OOA = c("OUT OF AREA"))

table(newShelter$Outcome.Type)
newShelter$Outcome.Type <- fct_collapse(newShelter$Outcome.Type, 
                           Adopted_Rescued = c("ADOPTION", "FOSTER TO ADOPT", "RESCUE"),
                           Not_Adopted = c("COMMUNITY CAT", "DIED", "DISPOSAL", "DUPLICATE", "EUTHANASIA", 
                                           "FOSTER", "MISSING", "RETURN TO OWNER", "RETURN TO RESCUE", 
                                           "RETURN TO WILD HABITAT", "SHELTER, NEUTER, RETURN", "TRANSFER", 
                                           "TRANSPORT", "TRAP, NEUTER, RELEASE"))
view(newShelter)
```

```{r}
normalize <- function(x){
 (x - min(x)) / (max(x) - min(x))
}

abc <- names(select_if(newShelter, is.numeric))

newShelter[abc] <- lapply(newShelter[abc], normalize)

newShelter[,c(3)] <- lapply(newShelter[,c(3)], as.factor) # converting characters to factors
```

```{r}
# one hot encoding
ab_c <- names(select_if(newShelter, is.factor))
newShelter <- one_hot(as.data.table(newShelter),cols=ab_c,sparsifyNAs = TRUE,naCols = FALSE,dropCols = TRUE,dropUnusedLevels = TRUE)

newShelter <- newShelter[,-27]


```